# Project-wide Gradle settings.
# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX package structure
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Resource namespacing
android.nonTransitiveRClass=true

# Suppress compile SDK 36 warning for early preview/adoption
android.suppressUnsupportedCompileSdk=36

# Suppress AGP & DSL Deprecation warnings
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL